// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbysxzwibmxusqslsbqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieXN4endpYm14dXNxc2xzYnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzAzMTUsImV4cCI6MjA2NjUwNjMxNX0.hHxjTSPPuOPE-lpN0v4BgrxyW9olK-ur65y6gxldZSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);